const homeText=[
    [
        "Who We Are",
        "<p>We offer alternative solutions for contact form UIs. Whether you are seeking to provide a more unique and spicy template for your applications and contact forms, or looking for a better way to screen out unmotivated clients, we got you covered.</p><p>Our number one priority is steamlining business communication by delivering you only the most serious and highly-motivated people. Whether you are a business entrepreneur hunting for talent to join your team or a freelancer looking for the next gig, we filter out all the subpar applications and deliver you a literal silver platter, loaded with hand-picked premium leads that will guarantee YOU and YOUR BUSINESS go places. </p><p>Stop wasting your time on pointless leads and second-tier talent. Upgrade your forms. Upgrade your opportunities.</p>"
    ],
    [
        "Our Vision",
        "<p>A world where talent-acquisition teams no longer have to sort through thousands of resumes and conduct dozens of interviews to find the right talent. A world where business can be conducted quick and efficiently, without wasting any time pursuing fruitless leads. A world where finding the brightest talent and the most motivated clients no longer resembles looking for a needle in a haystack, but rather looking for a needle in a needle warehouse.<p/>"
    ],
    [
        "Our Mission",
        "<p>Establish the first monopoloy in the online-form industry. Through disruptive innovation and strategic marketing, we will compete with the Big Form giants, plunder their market share, plummet their stock value, auction their assets and terminate their boards.</p>"
    ],
    [
        "Our Inspiration",
        "<p>It's four o'clock on a Friday afternoon. You have spent the entire week reviewing resumes, calling references, planning shift scheduling, and acting as a mediator in all sorts of employee conflict. The placard over your desk says \"HR Specialist\", but in reality, you feel like your job is to be dragged into everyone's playground drama. But it's okay because you are a people person.</p><p>After having poured over 300 resumes over the last few days and conducted dozens of phone and in-person interviews, you have finally found a perfect fit for the job opening the company posted a month ago. You spent dozens of hours looking for the best candidate, and you have found finally found one: young, from a prestigious school, with plenty of professional and leadership experience, without being overqualified or asking for fair compensation. You feel a sense of satisfaction and fulfillment; the refreshening breeze of having one less responsibility on your plate.</p><p>As you put on your thick framed glasses and pack your laptop into your hipster-brand leather briefcase, Mr. Lumbergh, the office manager, pops his head into your office.</p><p>\"Great job this week getting that new hire. Unfortunately, Sally from accounting just quit. Something about finding her calling in life in some Greek island. So if you could post a job opening for accounting before leaving today, that would be great. Great job on those TPS reports by the way\".</p><p>You open up the company's Indeed profile, copy and paste a generic post for an accounting job opening. You sprint accross the open floor space to avoid getting bogged down by employees asking last minute HR-related questions about PTO and other nonesense. You spend the next two days hanging with your Schnauzer and drinking mojitos with your S.O.</p><p>But Monday morning arrives. You come back to the office, ready to tackle another week of professional opportunities and challenges. You boot your computer and check the Indeed job opening you posted not even three days ago for that accounting opening Mr.Lumbergh told you about. Your jaw locks and your hands start shaking. Palms sweaty. Knees weak. Arms get heavy.</p><p>\"1529 resumes... in three days?... How?\", you whisper.</p><p>\"Hey, if you could submit those TPS reports ASAP, that would be great.\", Mr.Lumbergh says as he strolls past your office. Now you gotta go through all those resumes, make all those phone calls, conduct all those interviews. Just like you did the week before. And the week prior. And the week prior.</p><p>\"If only there was some type of software that could help me pre-screen applicants, weeding out the less motivated ones, and only feed me resumes of the most motivated and serious ones?\" is all you can wonder.</p>"
    ]
];

export default homeText