const oranges=[
    {
        id:'0',
        src:'/pictures/orange/apple.png'
    },
    {
        id:'1',
        src:'/pictures/orange/orange1.jpg'
    },
    {
        id:'2',
        src:'/pictures/orange/orange2.jpg'
    },
    {
        id:'3',
        src:'/pictures/orange/orange3.png'
    },
    {
        id:'4',
        src:'/pictures/orange/orange4.jpeg'
    },
    {
        id:'5',
        src:'/pictures/orange/orange5.jpg'
    },
    {
        id:'6',
        src:'/pictures/orange/orange6.jpg'
    },
    {
        id:'7',
        src:'/pictures/orange/orange7.png'
    },
    {
        id:'8',
        src:'/pictures/orange/orange8.jpg'
    }
]

export default oranges;